### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by kopax** [makkus/docker-seafile#3]
Do you have a working example ? 
I spent a day trying to make this project work. 
Also, you are referencing in nginx, data, and db seafile configuration.
Each composent (except seafile) should be replacable by an existing instance.

**Comment by makkus** [comment]
What exactly doesn't work? I just checked out a vanilla version of this repo and realized that the seafile version number in the default nginx example is an old one. Seafile changed their download location, so the download went nowhere and broke that part of the install. Anyway, if you change the version number in your docker-compose.yml to 4.2.3 (or delete the file alltogether and start fresh) and run 'first-time-setup.sh' it should work. If not, can you paste your error message in here?
